### ISSUE TITLE
Resultados de la revisión inicial

### ISSUE THREAD

**Issue by jmdaweb** [rayo-alcantar/TimeCalculator#2]
A continuación expongo los resultados de la revisión. Hay algunos puntos críticos que deberías resolver cuanto antes, y otros que te puedes tomar con más calma. Te los ordeno de mayor a menor importancia:

* El complemento es capaz de ejecutarse en pantallas seguras. Aunque no añada agujeros de seguridad, no parece muy útil en ese entorno y sería buena idea impedir su ejecución para no sobrecargar el lector.
* Faltan referencias a la licencia. En el código fuente del complemento, debes incluir cabeceras de copyright en forma de comentarios. Puedes inspirarte en otros complementos que ya las tienen. En el archivo buildVars.py tienes los campos de licencia configurados a None. Deberían estar del siguiente modo:
    * Nombre de licencia: GPL 2
    * URL de la licencia: https://www.gnu.org/licenses/gpl-2.0.html
* En buildVars.py, falta la URL del complemento. Puede coincidir con la del repositorio.
* En buildVars.py, se declaran los rangos de compatibilidad como números decimales, pero deberían ser cadenas. Basta con que los envuelvas entre comillas.
* En buildVars.py, la variable pythonSources está vacía. Para que el complemento sea traducible, debes incluir en ella la ruta de todos tus archivos .py. Por ejemplo, "addon/globalPlugins/timeCalculator.py".
* En el código fuente, las cadenas no son traducibles. Sé que hemos hablado de ello, pero aun así lo resalto por aquí para que no se nos pase. Se deben hacer traducibles envolviéndolas en una llamada a _(), llamando a addonHandler.initTranslation al principio del complemento, e incluyendo comentarios para traductores encima de todas ellas.
* Falta una opción para acceder a la interfaz del complemento en el menú Herramientas. No todos los usuarios tienen la capacidad de pulsar atajos de teclado. Aunque seguramente sean minoría, debemos acordarnos de aquellas personas que se manejan con el ratón y, quizá por una discapacidad motora, no puedan pulsar varias teclas a la vez. El menú se crea en el método __init__ del globalPlugin, y debe destruirse en el método terminate.
* Finalmente, veo una llamada a GlobalAlloc en la función que sitúa texto en el portapapeles. Esta llamada reserva memoria. ¿Cómo se libera esa memoria al terminar de usarla? Tal vez no haga falta modificar código en este caso, pero sí me gustaría una respuesta.

En cuanto estén resueltas las observaciones sobre seguridad y licencia, se podrá publicar.

**Comment by rayo-alcantar** [comment]
¡Muchas gracias por la corrección!
Ya he  hecho unos commits con la mayoría de ellos.
En cuanto a la función de GlobalAlloc, según tengo entendido, toma una parte de la memoria del sistema donde se coloca el texto.
Ya que tengo esa memoria, con GlobalLock se crea un puntero a la misma y se manda la información al espacio en memoria.
al final con GlobalUnlock si bien no se libera la memoria, sí se marca como que se a dejado de utilizar por el momento.

**Comment by jmdaweb** [comment]
En ese caso, tienes que buscar una forma de liberarla. Con cada llamada a la función estás reservando más y más, aunque luego no se utilice.

**Comment by rayo-alcantar** [comment]
Ou, muchas gracias, tenía entendido que windows se encargaba de eliminarla después de un tiempo,  pero lo veré junto a lo de la traducción. muchas gracias!

**Comment by jmdaweb** [comment]
Bien Rayo, ya casi lo tenemos! Algunos comentarios sobre los cambios que has hecho:

* Llamas a return si NVDA se ejecuta en modo seguro, pero el objeto se va a quedar instanciado igualmente. Eso puede dar problemas si el usuario pulsa el atajo, por ejemplo. Te recomiendo seguir un enfoque como el de [este ejemplo](https://github.com/nvda-es/ejemplos-codigo/blob/main/globalPlugins/inicio-retardado-tareas-de-red.py), y aprovechar el decorador incluido.
* El nombre que has puesto en pythonSources, en buildVars.py, no coincide con el nombre del archivo que tiene el código.
* El elemento que se añade al menú Herramientas no es traducible.

Y todo lo demás está bien, en cuanto arregles esas 3 cosas lo publicamos! Por cierto, no debería hacer falta el documento que tienes en addon/doc/es/readme.md, scons debería copiarlo de la raíz al compilar.

**Comment by rayo-alcantar** [comment]
¡Muchas gracias!
Ya está corregido al menos la parte del nombre que continee el código fuente, e intenté adecuar lo de las pantallas seguras, así como hacer traducible el item del menú herramientas.
En un momento libero la release.

**Comment by jmdaweb** [comment]
Buen trabajo! Doy la revisión por completada. Te aviso por otra vía tan pronto como puedas gestionar el complemento en la tienda de nvda.es. Sobre lo que nos quedó pendiente de la gestión de memoria, mírate la función api.copyToClip del propio NVDA. Tal vez te permita simplificar código y conseguir el mismo resultado.
